name: Call Reusable Workflow
on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: vaishaliarora01-gif/central_repository.github/workflows/common_temp.yaml@main
    with:
      environment: prod
